# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Not Bored' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Not Bored

  pod 'Alamofire', '~>5.4'

  # target 'Not BoredTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'Not BoredUITests' do
  #   # Pods for testing
  # end

end
